# Generated by Django 2.1.5 on 2019-02-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_time',
        ),
    ]
