# Generated by Django 2.1.5 on 2019-02-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0003_auto_20190222_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
