# Generated by Django 2.1.5 on 2019-02-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0004_auto_20190222_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
