# Generated by Django 2.1.5 on 2019-02-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0005_auto_20190222_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_pinned',
            field=models.NullBooleanField(default=False),
        ),
    ]
