# Generated by Django 2.1.5 on 2019-02-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0006_auto_20190222_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
