# Generated by Django 2.1.5 on 2019-03-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0007_auto_20190222_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
