# Generated by Django 2.1.5 on 2019-03-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0011_map_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='map_label',
            name='map_label_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
